name: Build and test pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out new code
        uses: actions/checkout@v3

      - name: Setup .Net5
        uses: actions/setup-dotnet@v1.0.0
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore BookStore.sln

      - name: Build
        run: dotnet build BookStore.sln -c Release --no-restore






